# Source: https://forum.strapi.io/t/nginx-proxing-with-strapi/40618

server {
    listen 80;
    server_name app.local;

    location / {
        proxy_pass http://nextjs:3000;
    }
}

server {
    listen 80;
    server_name cms.app.local;

    location / {
        proxy_pass http://strapi:1337;
    }
}




